//! TypeScript codegen for `cargo taut gen` (Phase 1 + 2 error narrowing).
//!
//! Pure logic: takes an [`ir::Ir`] document and renders a single
//! `api.gen.ts` source string. The CLI's `gen` subcommand owns the I/O and
//! validator-flag parsing; this module owns the string-building.
//!
//! See `SPEC.md` §3 (type mapping), §3.3/§4.1 (error envelope), and §6
//! (client API). The shape of the generated client mirrors the runtime
//! declarations in `npm/taut-rpc/src/index.ts` — every emitted procedure is
//! a `ProcedureDef<I, O, E, Kind>`, and the final `Procedures` type map is
//! what `createClient<Procedures>` consumes.
//!
//! Phase 2 additions:
//! - For each procedure with a non-empty error set we also emit a
//!   `Proc_<name>_Error` type alias right before its `ProcedureDef`. Callers
//!   import this alias to drive `e.code` narrowing without touching `unknown`.
//! - We emit a runtime `procedureKinds` const (`as const satisfies …`) so
//!   `createClient` can dispatch query vs. mutation vs. subscription without
//!   the caller having to thread the map manually. `createApi` defaults to
//!   it but still lets users override via `opts.kinds`.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use taut_rpc::ir::{
    EnumDef, Field, Ir, Procedure, TypeDef, TypeRef, TypeShape, Variant, VariantPayload,
};
use taut_rpc::type_map::{self, BigIntStrategy};

/// Validator runtime to target in the generated client.
///
/// Mirrors the CLI flag of the same name (see `commands/gen.rs`). For Phase 1
/// the `Valibot` and `Zod` choices only emit a TODO breadcrumb — the real
/// schema rendering is Phase 4.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Validator {
    Valibot,
    Zod,
    None,
}

/// Per-invocation knobs for [`render_ts`].
#[derive(Debug, Clone)]
pub struct CodegenOptions {
    pub validator: Validator,
    pub bigint_strategy: BigIntStrategy,
    /// Mirror of [`taut_rpc::type_map::Options::honor_undefined`].
    /// Controls whether `field: T | undefined` is emitted for fields the
    /// IR marks `undefined: true`.
    pub honor_undefined: bool,
}

impl Default for CodegenOptions {
    fn default() -> Self {
        Self {
            validator: Validator::Valibot,
            bigint_strategy: BigIntStrategy::Native,
            honor_undefined: true,
        }
    }
}

/// Render an [`Ir`] into a single `api.gen.ts` source string.
///
/// This is the panicking-on-internal-bug variant: duplicate type definitions
/// with conflicting bodies will panic. Use [`render_ts_checked`] when callers
/// want to recover from that case (e.g. surface a friendly CLI error).
#[must_use]
pub fn render_ts(ir: &Ir, opts: &CodegenOptions) -> String {
    render_ts_checked(ir, opts).expect("render_ts: duplicate TypeDef names disagree")
}

/// Fallible variant of [`render_ts`].
///
/// Errors only on a single, well-defined condition: two `TypeDef`s share a
/// name but have different bodies. Equal duplicates are silently deduped.
pub fn render_ts_checked(ir: &Ir, opts: &CodegenOptions) -> Result<String, String> {
    let mut out = String::new();
    let tm_opts = type_map_options(opts);

    write_header(&mut out, ir);
    write_imports(&mut out);
    write_types(&mut out, ir, &tm_opts)?;
    write_procedures(&mut out, ir, &tm_opts);
    write_procedures_map(&mut out, ir);
    write_procedure_kinds(&mut out, ir);
    write_create_api(&mut out);
    write_validator_stub(&mut out, opts.validator);

    Ok(out)
}

fn type_map_options(opts: &CodegenOptions) -> type_map::Options {
    type_map::Options {
        bigint: opts.bigint_strategy,
        honor_undefined: opts.honor_undefined,
    }
}

// ---------------------------------------------------------------------------
// Section emitters
// ---------------------------------------------------------------------------

fn write_header(out: &mut String, ir: &Ir) {
    let v = ir.ir_version;
    out.push_str("// DO NOT EDIT — generated by taut-rpc-cli.\n");
    out.push_str("// Re-run `cargo taut gen` to refresh.\n");
    let _ = writeln!(out, "// IR version: {v}");
    out.push('\n');
}

fn write_imports(out: &mut String) {
    out.push_str("import type { ProcedureDef } from \"taut-rpc\";\n");
    out.push_str(
        "import { createClient, type ClientOptions, type ClientOf } from \"taut-rpc\";\n\n",
    );
}

fn write_types(
    out: &mut String,
    ir: &Ir,
    tm_opts: &type_map::Options,
) -> Result<(), String> {
    // Dedup-by-name. Equal duplicates collapse silently; conflicting ones
    // are an error so we don't silently drop information.
    let mut seen: BTreeMap<&str, &TypeDef> = BTreeMap::new();
    let mut order: Vec<&TypeDef> = Vec::new();
    for t in &ir.types {
        match seen.get(t.name.as_str()) {
            Some(prev) if *prev == t => continue,
            Some(_) => {
                return Err(format!(
                    "duplicate TypeDef `{}` with conflicting bodies",
                    t.name
                ));
            }
            None => {
                seen.insert(t.name.as_str(), t);
                order.push(t);
            }
        }
    }

    for t in order {
        write_type_def(out, t, tm_opts);
    }
    Ok(())
}

fn write_type_def(out: &mut String, t: &TypeDef, tm_opts: &type_map::Options) {
    if let Some(doc) = &t.doc {
        write_doc_comment(out, doc, "");
    }
    match &t.shape {
        TypeShape::Struct(fields) => write_struct(out, &t.name, fields, tm_opts),
        TypeShape::Enum(e) => write_enum(out, &t.name, e, tm_opts),
        TypeShape::Tuple(elems) => {
            let name = &t.name;
            let rendered = type_map::render_type(&TypeRef::Tuple(elems.clone()), tm_opts);
            let _ = writeln!(out, "export type {name} = {rendered};\n");
        }
        TypeShape::Newtype(inner) | TypeShape::Alias(inner) => {
            let name = &t.name;
            let rendered = type_map::render_type(inner, tm_opts);
            let _ = writeln!(out, "export type {name} = {rendered};\n");
        }
    }
}

fn write_struct(out: &mut String, name: &str, fields: &[Field], tm_opts: &type_map::Options) {
    let _ = writeln!(out, "export interface {name} {{");
    for f in fields {
        write_field_line(out, f, tm_opts, "  ");
    }
    out.push_str("}\n\n");
}

fn write_field_line(out: &mut String, f: &Field, tm_opts: &type_map::Options, indent: &str) {
    if let Some(doc) = &f.doc {
        write_doc_comment(out, doc, indent);
    }
    let ty = type_map::render_type(&f.ty, tm_opts);
    let want_undefined = f.undefined && tm_opts.honor_undefined;
    let qmark = if f.optional { "?" } else { "" };
    let ty_with_undef = if want_undefined {
        format!("{ty} | undefined")
    } else {
        ty
    };
    let name = &f.name;
    let _ = writeln!(out, "{indent}{name}{qmark}: {ty_with_undef};");
}

fn write_enum(out: &mut String, name: &str, e: &EnumDef, tm_opts: &type_map::Options) {
    let _ = writeln!(out, "export type {name} =");
    if e.variants.is_empty() {
        // An empty enum is uninhabited; `never` is the closest TS analogue.
        out.push_str("  never;\n\n");
        return;
    }
    for (i, v) in e.variants.iter().enumerate() {
        let last = i + 1 == e.variants.len();
        let term = if last { ";" } else { "" };
        write_variant(out, &e.tag, v, tm_opts, term);
    }
    out.push('\n');
}

fn write_variant(
    out: &mut String,
    tag: &str,
    v: &Variant,
    tm_opts: &type_map::Options,
    terminator: &str,
) {
    match &v.payload {
        VariantPayload::Unit => {
            let _ = writeln!(
                out,
                "  | {{ {tag}: {variant} }}{terminator}",
                variant = quoted(&v.name),
            );
        }
        VariantPayload::Tuple(elems) => {
            if elems.is_empty() {
                let _ = writeln!(
                    out,
                    "  | {{ {tag}: {variant} }}{terminator}",
                    variant = quoted(&v.name),
                );
            } else {
                let inner: Vec<String> =
                    elems.iter().map(|t| type_map::render_type(t, tm_opts)).collect();
                let _ = writeln!(
                    out,
                    "  | {{ {tag}: {variant}, payload: [{payload}] }}{terminator}",
                    variant = quoted(&v.name),
                    payload = inner.join(", "),
                );
            }
        }
        VariantPayload::Struct(fields) => {
            if fields.is_empty() {
                let _ = writeln!(
                    out,
                    "  | {{ {tag}: {variant} }}{terminator}",
                    variant = quoted(&v.name),
                );
                return;
            }
            let _ = writeln!(
                out,
                "  | {{ {tag}: {variant},",
                variant = quoted(&v.name),
            );
            for (i, f) in fields.iter().enumerate() {
                let last = i + 1 == fields.len();
                let ty = type_map::render_type(&f.ty, tm_opts);
                let want_undefined = f.undefined && tm_opts.honor_undefined;
                let qmark = if f.optional { "?" } else { "" };
                let ty_with_undef = if want_undefined {
                    format!("{ty} | undefined")
                } else {
                    ty
                };
                let sep = if last { "" } else { "," };
                let fname = &f.name;
                let _ = writeln!(out, "      {fname}{qmark}: {ty_with_undef}{sep}");
            }
            let _ = writeln!(out, "    }}{terminator}");
        }
    }
}

fn write_procedures(out: &mut String, ir: &Ir, tm_opts: &type_map::Options) {
    if ir.procedures.is_empty() {
        return;
    }
    out.push_str("// ---- procedures ----\n\n");
    for p in &ir.procedures {
        write_procedure_alias(out, p, tm_opts);
    }
}

fn write_procedure_alias(out: &mut String, p: &Procedure, tm_opts: &type_map::Options) {
    if let Some(doc) = &p.doc {
        write_doc_comment(out, doc, "");
    }
    let alias = procedure_alias_name(&p.name);
    let input = type_map::render_type(&p.input, tm_opts);
    let output = type_map::render_type(&p.output, tm_opts);
    // Phase 3: surface the subscription dispatch hint in IntelliSense so
    // callers see the `.subscribe(input)` shape on hover. The matching
    // type-level dispatch lives in `ClientOf<P>` (see npm/taut-rpc/src/index.ts).
    if matches!(p.kind, taut_rpc::ir::ProcKind::Subscription) {
        out.push_str(
            "/** Subscription procedure — call via `.subscribe(input)`, returns AsyncIterable. */\n",
        );
    }
    let _ = writeln!(
        out,
        "// kind: {kind:?}, http: {method:?}, name: {name}",
        kind = p.kind,
        method = p.http_method,
        name = p.name,
    );

    // Phase 2: emit a per-procedure error alias when the procedure has any
    // declared errors, so callers can narrow on `.code` via the alias's
    // discriminant. Procedures with no errors keep `never` as the third
    // ProcedureDef type arg (same as Phase 1) and skip the alias entirely.
    let error_arg = if p.errors.is_empty() {
        "never".to_string()
    } else {
        let error_alias = procedure_error_alias_name(&p.name);
        let union = render_error_union(&p.errors, tm_opts);
        let _ = writeln!(
            out,
            "/** Wire-shape error union for procedure `{name}`. Narrow on `.code`. */",
            name = p.name,
        );
        let _ = writeln!(out, "export type {error_alias} = {union};");
        error_alias
    };

    let kind_lit = match p.kind {
        taut_rpc::ir::ProcKind::Query => "\"query\"",
        taut_rpc::ir::ProcKind::Mutation => "\"mutation\"",
        taut_rpc::ir::ProcKind::Subscription => "\"subscription\"",
    };
    let _ = writeln!(
        out,
        "export type {alias} = ProcedureDef<{input}, {output}, {error_arg}, {kind_lit}>;\n",
    );
}

fn render_error_union(errors: &[TypeRef], tm_opts: &type_map::Options) -> String {
    match errors.len() {
        0 => "never".to_string(),
        1 => type_map::render_type(&errors[0], tm_opts),
        _ => errors
            .iter()
            .map(|e| type_map::render_type(e, tm_opts))
            .collect::<Vec<_>>()
            .join(" | "),
    }
}

fn write_procedures_map(out: &mut String, ir: &Ir) {
    // Use a type alias (not an interface) so the literal shape's known keys
    // intersect cleanly with the runtime's `Record<string, ProcedureDef<...>>`
    // index signature. An interface without an index signature would not
    // satisfy the `extends Procedures` constraint on `ClientOf<P>`.
    out.push_str("export type Procedures = {\n");
    for p in &ir.procedures {
        let alias = procedure_alias_name(&p.name);
        let _ = writeln!(out, "  {key}: {alias};", key = quoted(&p.name));
    }
    out.push_str("};\n\n");
}

fn write_procedure_kinds(out: &mut String, ir: &Ir) {
    // Runtime-visible counterpart to the `Procedures` type map: the runtime
    // dispatches query vs. mutation vs. subscription from this table.
    // `as const satisfies …` pins each value to its narrow literal kind so
    // callers reading `procedureKinds.foo` see `"query"` (not `string`).
    out.push_str("/** Procedure name -> kind, for runtime dispatch. */\n");
    out.push_str("export const procedureKinds = {\n");
    for p in &ir.procedures {
        let kind_lit = match p.kind {
            taut_rpc::ir::ProcKind::Query => "\"query\"",
            taut_rpc::ir::ProcKind::Mutation => "\"mutation\"",
            taut_rpc::ir::ProcKind::Subscription => "\"subscription\"",
        };
        let _ = writeln!(
            out,
            "  {key}: {kind_lit},",
            key = quoted(&p.name),
        );
    }
    out.push_str(
        "} as const satisfies Record<keyof Procedures, \"query\" | \"mutation\" | \"subscription\">;\n\n",
    );
}

fn write_create_api(out: &mut String) {
    out.push_str("/** Construct a typed client for the procedures generated above. */\n");
    out.push_str("export function createApi(opts: ClientOptions): ClientOf<Procedures> {\n");
    out.push_str("  return createClient<Procedures>({ ...opts, kinds: opts.kinds ?? procedureKinds });\n");
    out.push_str("}\n");
}

fn write_validator_stub(out: &mut String, v: Validator) {
    if matches!(v, Validator::None) {
        return;
    }
    out.push('\n');
    out.push_str("// TODO: validator schemas (Phase 4)\n");
    let _ = writeln!(out, "// (configured validator: {v:?})");
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Turn a dotted procedure name like `"users.get"` into a TS identifier
/// `"Proc_users_get"`. Non-identifier characters beyond `.` are also
/// replaced, so `"users-list"` → `"Proc_users_list"`.
fn procedure_alias_name(proc_name: &str) -> String {
    let mut s = String::with_capacity(5 + proc_name.len());
    s.push_str("Proc_");
    for ch in proc_name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            s.push(ch);
        } else {
            s.push('_');
        }
    }
    s
}

/// Companion to [`procedure_alias_name`] for the per-procedure error union
/// alias. `"users.get"` → `"Proc_users_get_Error"`.
fn procedure_error_alias_name(proc_name: &str) -> String {
    let mut s = procedure_alias_name(proc_name);
    s.push_str("_Error");
    s
}

/// Quote a string as a TS string literal. We don't need full JSON escaping
/// here because the inputs are Rust idents / dotted names by construction;
/// still, we escape the obvious troublemakers defensively.
fn quoted(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

/// Render a doc comment (`/** ... */`) at the given indent, splitting on
/// newlines so multi-line Rust doc comments survive the trip.
fn write_doc_comment(out: &mut String, doc: &str, indent: &str) {
    let lines: Vec<&str> = doc.lines().collect();
    if lines.len() == 1 {
        let body = lines[0].trim();
        let _ = writeln!(out, "{indent}/** {body} */");
        return;
    }
    let _ = writeln!(out, "{indent}/**");
    for line in lines {
        let body = line.trim_end();
        let _ = writeln!(out, "{indent} * {body}");
    }
    let _ = writeln!(out, "{indent} */");
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use taut_rpc::ir::{
        EnumDef, Field, HttpMethod, Ir, Primitive, ProcKind, Procedure, TypeDef, TypeRef,
        TypeShape, Variant, VariantPayload,
    };

    fn opts() -> CodegenOptions {
        CodegenOptions::default()
    }

    fn opts_no_validator() -> CodegenOptions {
        CodegenOptions {
            validator: Validator::None,
            ..CodegenOptions::default()
        }
    }

    #[test]
    fn empty_ir_emits_header_imports_and_empty_procedures_map() {
        let ir = Ir::empty();
        let s = render_ts(&ir, &opts_no_validator());
        assert!(s.contains("DO NOT EDIT"), "header missing:\n{s}");
        assert!(
            s.contains("import type { ProcedureDef } from \"taut-rpc\";"),
            "type-only import missing:\n{s}"
        );
        assert!(
            s.contains("import { createClient, type ClientOptions, type ClientOf } from \"taut-rpc\";"),
            "value import missing:\n{s}"
        );
        assert!(
            s.contains("export type Procedures = {\n};"),
            "empty Procedures map missing:\n{s}"
        );
        assert!(
            s.contains("export const procedureKinds = {\n} as const satisfies Record<keyof Procedures, \"query\" | \"mutation\" | \"subscription\">;"),
            "empty procedureKinds missing:\n{s}"
        );
        assert!(
            s.contains("export function createApi(opts: ClientOptions): ClientOf<Procedures>"),
            "createApi missing:\n{s}"
        );
        assert!(
            s.contains("createClient<Procedures>({ ...opts, kinds: opts.kinds ?? procedureKinds });"),
            "createApi should thread procedureKinds through to createClient:\n{s}"
        );
    }

    #[test]
    fn one_query_string_to_u32_emits_proc_alias() {
        let ir = Ir {
            ir_version: Ir::CURRENT_VERSION,
            procedures: vec![Procedure {
                name: "ping".to_string(),
                kind: ProcKind::Query,
                input: TypeRef::Primitive(Primitive::String),
                output: TypeRef::Primitive(Primitive::U32),
                errors: vec![],
                http_method: HttpMethod::Post,
                doc: None,
            }],
            types: vec![],
        };
        let s = render_ts(&ir, &opts_no_validator());
        assert!(
            s.contains("export type Proc_ping = ProcedureDef<string, number, never, \"query\">;"),
            "proc alias wrong:\n{s}"
        );
        assert!(
            s.contains("\"ping\": Proc_ping;"),
            "Procedures key wrong:\n{s}"
        );
        // Zero-error procedure -> no `_Error` alias emitted.
        assert!(
            !s.contains("Proc_ping_Error"),
            "zero-error procedure must not emit error alias:\n{s}"
        );
        // procedureKinds runtime map should mention the procedure name -> kind.
        assert!(
            s.contains("\"ping\": \"query\","),
            "procedureKinds entry missing:\n{s}"
        );
    }

    #[test]
    fn dotted_procedure_name_becomes_underscored_alias() {
        assert_eq!(procedure_alias_name("users.get"), "Proc_users_get");
        assert_eq!(procedure_alias_name("ping"), "Proc_ping");
        assert_eq!(procedure_alias_name("a.b.c"), "Proc_a_b_c");
    }

    #[test]
    fn struct_typedef_emits_interface_with_all_three_field_modes() {
        let ir = Ir {
            ir_version: Ir::CURRENT_VERSION,
            procedures: vec![],
            types: vec![TypeDef {
                name: "User".to_string(),
                doc: None,
                shape: TypeShape::Struct(vec![
                    // plain
                    Field {
                        name: "id".to_string(),
                        ty: TypeRef::Primitive(Primitive::U32),
                        optional: false,
                        undefined: false,
                        doc: None,
                    },
                    // optional
                    Field {
                        name: "nickname".to_string(),
                        ty: TypeRef::Primitive(Primitive::String),
                        optional: true,
                        undefined: false,
                        doc: None,
                    },
                    // undefined-flavored
                    Field {
                        name: "tagline".to_string(),
                        ty: TypeRef::Primitive(Primitive::String),
                        optional: false,
                        undefined: true,
                        doc: None,
                    },
                    // both
                    Field {
                        name: "avatar".to_string(),
                        ty: TypeRef::Primitive(Primitive::String),
                        optional: true,
                        undefined: true,
                        doc: None,
                    },
                ]),
            }],
        };
        let s = render_ts(&ir, &opts_no_validator());
        assert!(s.contains("export interface User {"), "no interface:\n{s}");
        assert!(s.contains("id: number;"), "plain field wrong:\n{s}");
        assert!(s.contains("nickname?: string;"), "optional wrong:\n{s}");
        assert!(
            s.contains("tagline: string | undefined;"),
            "undefined wrong:\n{s}"
        );
        assert!(
            s.contains("avatar?: string | undefined;"),
            "both wrong:\n{s}"
        );
    }

    #[test]
    fn enum_typedef_emits_discriminated_union() {
        let ir = Ir {
            ir_version: Ir::CURRENT_VERSION,
            procedures: vec![],
            types: vec![TypeDef {
                name: "Event".to_string(),
                doc: None,
                shape: TypeShape::Enum(EnumDef {
                    tag: "type".to_string(),
                    variants: vec![
                        Variant {
                            name: "Ping".to_string(),
                            payload: VariantPayload::Unit,
                        },
                        Variant {
                            name: "Message".to_string(),
                            payload: VariantPayload::Tuple(vec![TypeRef::Primitive(
                                Primitive::String,
                            )]),
                        },
                        Variant {
                            name: "Move".to_string(),
                            payload: VariantPayload::Struct(vec![
                                Field {
                                    name: "x".to_string(),
                                    ty: TypeRef::Primitive(Primitive::I32),
                                    optional: false,
                                    undefined: false,
                                    doc: None,
                                },
                                Field {
                                    name: "y".to_string(),
                                    ty: TypeRef::Primitive(Primitive::I32),
                                    optional: false,
                                    undefined: false,
                                    doc: None,
                                },
                            ]),
                        },
                    ],
                }),
            }],
        };
        let s = render_ts(&ir, &opts_no_validator());
        assert!(s.contains("export type Event ="), "header missing:\n{s}");
        assert!(
            s.contains("{ type: \"Ping\" }"),
            "unit variant wrong:\n{s}"
        );
        assert!(
            s.contains("{ type: \"Message\", payload: [string] }"),
            "tuple variant wrong:\n{s}"
        );
        assert!(
            s.contains("{ type: \"Move\","),
            "struct variant header wrong:\n{s}"
        );
        assert!(s.contains("x: number"), "x field wrong:\n{s}");
        assert!(s.contains("y: number"), "y field wrong:\n{s}");
    }

    #[test]
    fn newtype_and_alias_emit_type_aliases() {
        let ir = Ir {
            ir_version: Ir::CURRENT_VERSION,
            procedures: vec![],
            types: vec![
                TypeDef {
                    name: "UserId".to_string(),
                    doc: None,
                    shape: TypeShape::Newtype(TypeRef::Primitive(Primitive::U64)),
                },
                TypeDef {
                    name: "Maybe".to_string(),
                    doc: None,
                    shape: TypeShape::Alias(TypeRef::Option(Box::new(TypeRef::Primitive(
                        Primitive::String,
                    )))),
                },
                TypeDef {
                    name: "Pair".to_string(),
                    doc: None,
                    shape: TypeShape::Tuple(vec![
                        TypeRef::Primitive(Primitive::I32),
                        TypeRef::Primitive(Primitive::String),
                    ]),
                },
            ],
        };
        let s = render_ts(&ir, &opts_no_validator());
        assert!(
            s.contains("export type UserId = bigint;"),
            "newtype wrong:\n{s}"
        );
        assert!(
            s.contains("export type Maybe = string | null;"),
            "alias wrong:\n{s}"
        );
        assert!(
            s.contains("export type Pair = [number, string];"),
            "tuple wrong:\n{s}"
        );
    }

    #[test]
    fn duplicate_typedefs_with_equal_bodies_dedup_silently() {
        let dup = TypeDef {
            name: "Same".to_string(),
            doc: None,
            shape: TypeShape::Newtype(TypeRef::Primitive(Primitive::U32)),
        };
        let ir = Ir {
            ir_version: Ir::CURRENT_VERSION,
            procedures: vec![],
            types: vec![dup.clone(), dup],
        };
        let s = render_ts_checked(&ir, &opts_no_validator()).expect("dedup ok");
        let count = s.matches("export type Same = number;").count();
        assert_eq!(count, 1, "should appear exactly once:\n{s}");
    }

    #[test]
    fn duplicate_typedefs_with_conflicting_bodies_error() {
        let a = TypeDef {
            name: "Same".to_string(),
            doc: None,
            shape: TypeShape::Newtype(TypeRef::Primitive(Primitive::U32)),
        };
        let b = TypeDef {
            name: "Same".to_string(),
            doc: None,
            shape: TypeShape::Newtype(TypeRef::Primitive(Primitive::String)),
        };
        let ir = Ir {
            ir_version: Ir::CURRENT_VERSION,
            procedures: vec![],
            types: vec![a, b],
        };
        let err = render_ts_checked(&ir, &opts_no_validator()).unwrap_err();
        assert!(err.contains("Same"), "err should mention name: {err}");
    }

    #[test]
    fn multiple_errors_render_as_union() {
        let ir = Ir {
            ir_version: Ir::CURRENT_VERSION,
            procedures: vec![Procedure {
                name: "p".to_string(),
                kind: ProcKind::Mutation,
                input: TypeRef::Primitive(Primitive::Unit),
                output: TypeRef::Primitive(Primitive::Unit),
                errors: vec![
                    TypeRef::Named("NotFound".to_string()),
                    TypeRef::Named("Unauthorized".to_string()),
                ],
                http_method: HttpMethod::Post,
                doc: None,
            }],
            types: vec![],
        };
        let s = render_ts(&ir, &opts_no_validator());
        // Phase 2: the alias is emitted before the ProcedureDef and the
        // ProcedureDef's third type arg references the alias rather than
        // the inline union.
        assert!(
            s.contains("export type Proc_p_Error = NotFound | Unauthorized;"),
            "per-procedure error alias missing:\n{s}"
        );
        assert!(
            s.contains("export type Proc_p = ProcedureDef<void, void, Proc_p_Error, \"mutation\">;"),
            "ProcedureDef should reference Proc_p_Error alias:\n{s}"
        );
        // Sanity: the alias must appear *before* the ProcedureDef so TS
        // resolves the forward reference cleanly.
        let alias_idx = s
            .find("export type Proc_p_Error =")
            .expect("alias present");
        let def_idx = s
            .find("export type Proc_p =")
            .expect("def present");
        assert!(alias_idx < def_idx, "alias must precede ProcedureDef:\n{s}");
        // procedureKinds reflects the mutation kind for runtime dispatch.
        assert!(
            s.contains("\"p\": \"mutation\","),
            "procedureKinds entry missing:\n{s}"
        );
    }

    #[test]
    fn single_error_emits_error_alias() {
        let ir = Ir {
            ir_version: Ir::CURRENT_VERSION,
            procedures: vec![Procedure {
                name: "add".to_string(),
                kind: ProcKind::Query,
                input: TypeRef::Primitive(Primitive::Unit),
                output: TypeRef::Primitive(Primitive::U32),
                errors: vec![TypeRef::Named("AddError".to_string())],
                http_method: HttpMethod::Post,
                doc: None,
            }],
            types: vec![],
        };
        let s = render_ts(&ir, &opts_no_validator());
        assert!(
            s.contains("export type Proc_add_Error = AddError;"),
            "single-error alias missing:\n{s}"
        );
        assert!(
            s.contains("export type Proc_add = ProcedureDef<void, number, Proc_add_Error, \"query\">;"),
            "ProcedureDef must reference single-error alias:\n{s}"
        );
        // Doc comment on the alias mentions narrowing.
        assert!(
            s.contains("Wire-shape error union for procedure `add`. Narrow on `.code`."),
            "alias doc comment missing or wrong:\n{s}"
        );
    }

    #[test]
    fn dotted_procedure_name_emits_dotted_error_alias() {
        let ir = Ir {
            ir_version: Ir::CURRENT_VERSION,
            procedures: vec![Procedure {
                name: "users.get".to_string(),
                kind: ProcKind::Query,
                input: TypeRef::Primitive(Primitive::U32),
                output: TypeRef::Named("User".to_string()),
                errors: vec![TypeRef::Named("NotFound".to_string())],
                http_method: HttpMethod::Get,
                doc: None,
            }],
            types: vec![],
        };
        let s = render_ts(&ir, &opts_no_validator());
        assert!(
            s.contains("export type Proc_users_get_Error = NotFound;"),
            "dotted-name error alias missing:\n{s}"
        );
        assert!(
            s.contains(
                "export type Proc_users_get = ProcedureDef<number, User, Proc_users_get_Error, \"query\">;"
            ),
            "dotted-name ProcedureDef wrong:\n{s}"
        );
        assert_eq!(procedure_error_alias_name("users.get"), "Proc_users_get_Error");
    }

    #[test]
    fn procedure_kinds_const_emitted_with_satisfies_clause() {
        let ir = Ir {
            ir_version: Ir::CURRENT_VERSION,
            procedures: vec![
                Procedure {
                    name: "ping".to_string(),
                    kind: ProcKind::Query,
                    input: TypeRef::Primitive(Primitive::Unit),
                    output: TypeRef::Primitive(Primitive::String),
                    errors: vec![],
                    http_method: HttpMethod::Post,
                    doc: None,
                },
                Procedure {
                    name: "do_thing".to_string(),
                    kind: ProcKind::Mutation,
                    input: TypeRef::Primitive(Primitive::Unit),
                    output: TypeRef::Primitive(Primitive::Unit),
                    errors: vec![],
                    http_method: HttpMethod::Post,
                    doc: None,
                },
                Procedure {
                    name: "events".to_string(),
                    kind: ProcKind::Subscription,
                    input: TypeRef::Primitive(Primitive::Unit),
                    output: TypeRef::Primitive(Primitive::String),
                    errors: vec![],
                    http_method: HttpMethod::Get,
                    doc: None,
                },
            ],
            types: vec![],
        };
        let s = render_ts(&ir, &opts_no_validator());
        assert!(
            s.contains("export const procedureKinds = {"),
            "procedureKinds const missing:\n{s}"
        );
        assert!(s.contains("\"ping\": \"query\","), "ping entry:\n{s}");
        assert!(
            s.contains("\"do_thing\": \"mutation\","),
            "do_thing entry:\n{s}"
        );
        assert!(
            s.contains("\"events\": \"subscription\","),
            "events entry:\n{s}"
        );
        assert!(
            s.contains("} as const satisfies Record<keyof Procedures, \"query\" | \"mutation\" | \"subscription\">;"),
            "as-const-satisfies tail missing:\n{s}"
        );
    }

    #[test]
    fn subscription_procedure_emits_subscription_kind_in_alias_and_kinds_map() {
        let ir = Ir {
            ir_version: Ir::CURRENT_VERSION,
            procedures: vec![Procedure {
                name: "ticker".to_string(),
                kind: ProcKind::Subscription,
                input: TypeRef::Primitive(Primitive::U32),
                output: TypeRef::Primitive(Primitive::String),
                errors: vec![],
                http_method: HttpMethod::Get,
                doc: None,
            }],
            types: vec![],
        };
        let s = render_ts(&ir, &opts_no_validator());
        // (1) The ProcedureDef carries the `"subscription"` literal — this is
        // what `ClientOf<P>` keys off to dispatch to `.subscribe(input)`.
        assert!(
            s.contains(
                "export type Proc_ticker = ProcedureDef<number, string, never, \"subscription\">;"
            ),
            "subscription proc alias wrong:\n{s}"
        );
        // (2) The runtime kinds map records `"subscription"` (not `"query"`).
        assert!(
            s.contains("\"ticker\": \"subscription\","),
            "procedureKinds entry must record subscription kind:\n{s}"
        );
        // (3) The JSDoc hint is emitted above the alias so editors surface the
        //     `.subscribe(input)` shape on hover.
        assert!(
            s.contains(
                "/** Subscription procedure — call via `.subscribe(input)`, returns AsyncIterable. */"
            ),
            "subscription JSDoc hint missing:\n{s}"
        );
        // Sanity: the JSDoc must precede the `Proc_ticker` alias declaration.
        let jsdoc_idx = s
            .find("Subscription procedure — call via")
            .expect("jsdoc present");
        let alias_idx = s
            .find("export type Proc_ticker =")
            .expect("alias present");
        assert!(
            jsdoc_idx < alias_idx,
            "JSDoc must precede the type alias:\n{s}"
        );
    }

    #[test]
    fn validator_stub_present_when_not_none() {
        let s = render_ts(&Ir::empty(), &opts());
        assert!(
            s.contains("TODO: validator schemas (Phase 4)"),
            "stub missing:\n{s}"
        );
    }

    #[test]
    fn validator_stub_absent_when_none() {
        let s = render_ts(&Ir::empty(), &opts_no_validator());
        assert!(
            !s.contains("validator schemas (Phase 4)"),
            "stub should be absent:\n{s}"
        );
    }
}
