// Phase 5 Todo UI.
//
// The entire wire surface is read from `./api.gen` (generated by
// `cargo taut gen`). We hand-write zero RPC code: `createApi` returns a
// fully typed proxy whose method names match the Rust `#[rpc]` functions,
// and `procedureSchemas` carries the per-procedure Valibot schemas so
// validation runs on every send/recv.
//
// State strategy:
//   - `list` is the rendered list. Initial value comes from `list_todos()`
//     on mount, then `todos_changed.subscribe()` replaces it on every
//     server-pushed frame. We never edit `list` ourselves after a
//     create/toggle — the broadcast frame is authoritative, which keeps
//     two open tabs in sync without optimistic-update reconciliation.
//   - `title` is the controlled input. We clear it on submit success.
//   - `err` shows the most recent client-side validation rejection or
//     transport error. Surfacing it makes the empty-title case visible
//     when the Valibot schema rejects pre-network.

import { useEffect, useState, type FormEvent } from "react";
import { createApi, procedureSchemas, type Todo } from "./api.gen";
import { isTautError } from "taut-rpc";

// `url: "/rpc"` is relative — Vite's dev server proxies it to the Rust
// server (see vite.config.ts). In a deploy this stays unchanged behind any
// reverse proxy that forwards `/rpc/*`.
//
// `schemas: procedureSchemas` opts every procedure into client-side
// validation by default. The empty-title case below fails synchronously
// here, before any network call, with `code: "validation_error"`.
const api = createApi({
  url: "/rpc",
  schemas: procedureSchemas,
});

export function App(): JSX.Element {
  const [list, setList] = useState<Todo[]>([]);
  const [title, setTitle] = useState("");
  const [err, setErr] = useState("");

  // Initial fetch + live subscription. Effect runs once on mount and the
  // returned cleanup fires on unmount. `cancelled` guards against late
  // resolution after unmount (StrictMode double-mounts in dev would otherwise
  // leak a stale `setList`).
  useEffect(() => {
    let cancelled = false;

    // Seed the list once. Subscriptions also emit the current snapshot on
    // connect so this is technically redundant, but it lets the UI render
    // immediately rather than waiting for the SSE handshake.
    api
      .list_todos()
      .then((todos) => {
        if (!cancelled) setList(todos);
      })
      .catch((e: unknown) => {
        if (!cancelled) setErr(formatError(e));
      });

    // Live updates. Each yielded frame is the full list; we replace state
    // outright rather than merging. The `for await` loop terminates when
    // the iterator throws (transport error) or returns (cleanup below).
    const stream = api.todos_changed.subscribe();
    (async () => {
      try {
        for await (const todos of stream) {
          if (cancelled) break;
          setList(todos);
        }
      } catch (e) {
        if (!cancelled) setErr(formatError(e));
      }
    })();

    return () => {
      cancelled = true;
      // Best-effort cancel: AsyncIterable returned by createApi.subscribe
      // cancels the underlying SSE on iterator return/throw. We can't call
      // `.return()` directly here because we never held the iterator object,
      // but `cancelled = true` plus the `break` above causes the loop to
      // exit on the next frame, which triggers the iterator's cleanup.
    };
  }, []);

  async function onSubmit(e: FormEvent): Promise<void> {
    e.preventDefault();
    setErr("");
    try {
      // Client-side validation runs INSIDE this call: an empty `title`
      // throws TautError("validation_error") before any network round-trip.
      await api.create_todo({ title });
      setTitle("");
      // Don't update `list` here — the subscription frame will bring the
      // authoritative new state.
    } catch (e: unknown) {
      setErr(formatError(e));
    }
  }

  async function onToggle(t: Todo): Promise<void> {
    setErr("");
    try {
      await api.complete_todo({ id: t.id, completed: !t.completed });
      // Same as above: trust the broadcast frame.
    } catch (e: unknown) {
      setErr(formatError(e));
    }
  }

  return (
    <>
      <h1>todo-react</h1>
      <p className="sub">taut-rpc Phase 5 demo · live via SSE subscription</p>

      <form onSubmit={onSubmit}>
        <input
          type="text"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="What needs doing?"
          aria-label="new todo title"
        />
        <button type="submit">Add</button>
      </form>

      <div className="err" role="alert">
        {err}
      </div>

      {list.length === 0 ? (
        <p className="empty">No todos yet. Add one above.</p>
      ) : (
        <ul>
          {list.map((t) => (
            <li key={t.id} className={t.completed ? "done" : ""}>
              <input
                type="checkbox"
                checked={t.completed}
                onChange={() => onToggle(t)}
                aria-label={`mark "${t.title}" ${t.completed ? "active" : "done"}`}
              />
              <span onClick={() => onToggle(t)} style={{ cursor: "pointer", flex: 1 }}>
                {t.title}
              </span>
            </li>
          ))}
        </ul>
      )}
    </>
  );
}

/**
 * Render any thrown value as a short string for the `.err` row.
 *
 * Validation rejections come back as `TautError("validation_error", { issues })`
 * — we flatten the issues array to its first message so the user sees
 * "Invalid length" rather than `[object Object]`. Every other error renders
 * as `code: <message>` (or just the message).
 */
function formatError(e: unknown): string {
  if (isTautError(e, "validation_error")) {
    const payload = e.payload as { issues?: Array<{ message?: string }> } | null;
    const first = payload?.issues?.[0]?.message;
    return first ? `Invalid input: ${first}` : "Invalid input";
  }
  if (isTautError(e)) {
    return `${e.code}: ${e.message}`;
  }
  if (e instanceof Error) return e.message;
  return String(e);
}
